server:
  port: 8090


person:
     lastName: tom
     age: 18
     boss: false
     birth: 2020/07/02
     map: {k1: v1,k2: v2}
     list:
       - lisi
       - wangwu
     dog:
       name: 小狗
       age: 2